### ISSUE TITLE
Subscription data format

### ISSUE THREAD

**Issue by rohitmohan96** [iot-onboarding/non-ip-iot-control#20]
We need to describe in the draft the details of the various data formats and the exact fields that each format will include from the data_app.proto. 
https://github.com/iot-onboarding/non-ip-iot-control/blob/d2e9b5eacbcf308945107ccf77c65c2622ae302a/nipc-openapi/NIPC_REST.yaml#L2858-L2867

We also have a `timestamped` data format but there is no timestamp field in the `DataSubscription` message that we publish on MQTT (I will create a PR for this soon).

**Comment by rohitmohan96** [comment]
I have removed the `timestamped` format from the yaml and added a timestamp field in the `DataSubscription` message in #22. 
I will add the text soon.

**Comment by bbrinckman** [comment]
fixed in 0.6.0
