### ISSUE TITLE
Topic registration

### ISSUE THREAD

**Issue by rohitmohan96** [iot-onboarding/non-ip-iot-control#21]
Couple of comments on the topic registration APIs: 
1. POST/PUT API: There is no `id` field present. I think this will be required to denote which devices' advertisements/gatt notifications/connection status will be published to the topic. 
2. GET API: The GET API response is a `MultiTopicsResponse` which consists of only a list of topics. We should be returning the parameters that were used during topic creation. 
3. GET/DELETE API: The API takes a topic as a query parameter. The API description says that this can be a comma separated list of topics or a group id. We don't have a separate group id parameter as of now. Also, I'm not a huge fan of comma separated lists in query parameters since clients/servers can sometimes disagree on how to encode the string. I think we should have this API be a GET ALL topics API since we also have separate "topic by id" and "topic by name" APIs. 
https://github.com/iot-onboarding/non-ip-iot-control/blob/d2e9b5eacbcf308945107ccf77c65c2622ae302a/nipc-openapi/NIPC_REST.yaml#L1371-L1388

**Comment by bbrinckman** [comment]
fixed in 0.6.0 in draft01 branch
